import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Col, Row, Container } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import { SocialData } from "../component/data/dataArr";

import Next from "../public/right.png";

export default function Home() {
  const videoUrl = "/background.mp4";
  const profileUrl = "/man.jpg";
  return (
    <div className={styles.container}>
      <Head>
        <title>Idemeto Emediong</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className={styles.main}>
          <video className={styles.video} loop autoPlay muted>
            <source src={videoUrl} type="video/mp4" />
          </video>
        </div>
        <section className={styles.section}>
          <div className={styles.profilePicture}>
            <Image
              src={profileUrl}
              alt="profilePicture"
              height={130}
              width={130}
              quality={70}
              className={styles.profileImage}
            />
          </div>
          <div className={styles.profileName}>
            <h3>Idemeto Emediong</h3>
          </div>
          <div className={styles.role}>
            <p>Front-End | Web Developer | Freelance</p>
          </div>
          <div className={styles.personalPortfolio}>
            <h2>Personal</h2>
          </div>
          <div className={styles.portfolio}>
            <Link href="/">
              <a>
                <button>portfolio</button>
              </a>
            </Link>
          </div>
          <div className={styles.socialPortfolio}>
            <h2>Socials</h2>
          </div>
          <Container>
            <Row>
              {SocialData.map((data) => (
                <Col key={data.id}>
                  <Link href={data.url}>
                    <a>
                      <div className={styles.socialIcons} key={data.id}>
                        <div className={styles.icon}>
                          <Image
                            src={data.img}
                            alt="social"
                            height={40}
                            width={40}
                          />
                        </div>
                        <div className={styles.social}>
                          <p>{data.Status}</p>
                          <p>{data.followers}</p>
                        </div>
                      </div>
                    </a>
                  </Link>
                </Col>
              ))}
            </Row>
          </Container>
        </section>
      </main>
    </div>
  );
}
